<%@page import="com.common.ClsCommon"%>
<%@page import="com.connection.*"%>
<%@page import="java.sql.*"%>
<%
String result="";
int errorstatus=0;
Connection conn=null;
String brhid=request.getParameter("brhid")==null?"":request.getParameter("brhid");
try{
	ClsConnection objconn=new ClsConnection();
	conn=objconn.getMyConnection();
	Statement stmt=conn.createStatement();
	String sqltest="";
	if(!brhid.equalsIgnoreCase("") && !brhid.equalsIgnoreCase("a")){
		sqltest+=" and brhid="+brhid;
	}
	String strcountdata="select (select count(*) as mrp from(select if(coalesce(mp.psrno,0)>0,'Y','N')MRP  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR')     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(mp.psrno,0)>0,'Y','N')MRP  from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR')   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.mrp='N')mrp,"+
			"(select count(*) as wo from(select if(coalesce(wk.doc_no,0)>0,'Y','N')WO  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.doc_no,0)>0,'Y','N')WO from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.wo='N')wo,"+
			"(select count(*) as blnd from(select if(coalesce(wk.blendsheetno,0)>0,'Y','N')BLND  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.blendsheetno,0)>0,'Y','N')BLND from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.blnd='N')blnd,"+
			"(select count(*) as MR from(select if(coalesce(wk.materialrequestno,0)>0,'Y','N')MR  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.materialrequestno,0)>0,'Y','N')MR from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.MR='N')mr,"+
			"(select count(*) as MIN from(select if(coalesce(wk.minno,0)>0,'Y','N')MIN  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.minno,0)>0,'Y','N')MIN from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.MIN='N')min,"+
			"(select count(*) as qa from(select if(coalesce(wk.qualityno,0)>0,'Y','N')QA  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.qualityno,0)>0,'Y','N')QA from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.qa='N')qa,"+
			"(select count(*) as pc from(select if(coalesce(wk.workprocess,0)=9,'Y','N')PC  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and d.rdocno=mp.rdocno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(wk.workprocess,0)=9,'Y','N')PC from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)  left join my_mrp mp on (if(mm.mainpsrno>0,mm.mainpsrno,d.psrno)=mp.psrno and mp.rdtype='SOR') left join my_workorder wk on mp.dpsrno=wk.psrno   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.pc='N')pc,"+
			"(select count(*) as fp from(select if(coalesce(d.fillqty,0)>0,'Y','N')FP  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)    where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(d.fillqty,0)>0,'Y','N')FP from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.fp='N')fp,"+
			"(select count(*) as del from(select if(coalesce(d.delno,0)>0,'Y','N')DEL  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno) where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(d.delno,0)>0,'Y','N')DEL from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.del='N')del,"+
			"(select count(*) as inv from(select if(coalesce(d.invno,0)>0,'Y','N')INV  from my_sorderm m left join my_sorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)     where m.status<>7   group by d.prdid,m.doc_no union all select if(coalesce(d.invno,0)>0,'Y','N')INV from my_stockorderm m  left join my_stockorderd d on d.rdocno=m.doc_no left join my_main mm on (mm.doc_no=d.prdid and d.psrno=mm.psrno)   where m.status<>7  group by d.prdid,m.doc_no)sl where sl.inv='N')inv";
	System.out.println("countdataqry===="+strcountdata);
	ResultSet rs=stmt.executeQuery(strcountdata);
	while(rs.next()){
		result=rs.getString("mrp")+"::"+rs.getString("wo")+"::"+rs.getString("blnd")+"::"+rs.getString("mr")+"::"+rs.getString("min")+"::"+rs.getString("qa")+"::"+rs.getString("pc")+"::"+rs.getString("fp")+"::"+rs.getString("del")+"::"+rs.getString("inv");
	}
}
catch(Exception e){
	e.printStackTrace();
}
finally{
	conn.close();
}
response.getWriter().write(result);
%>